name: GitHub Actions Build and Deploy

# 触发条件: push 到 master 分支后
on:
  workflow_dispatch:
  repository_dispatch:
    types: [build-and-deploy]
  push:
    branches:
      - main
    # 只在下列路径变更时触发
    paths:
      - 'docs/**'
      - 'package.json'

# 设置权限
permissions: write-all

# 设置上海时区
env:
  TZ: Asia/Shanghai

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 安装 pnpm
      - name: 安装 pnpm
        uses: pnpm/action-setup@v4

      # 设置 node 版本
      - name: 安装 NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: 拷贝文件
        run: cp README.md ./dist/

      # 部署
      - name: 部署站点
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACCESS_TOKEN: ${{ secrets.DEVELOP_DOC }}
          BRANCH: gh-pages
          FOLDER: .vuepress/dist
          COMMIT_MESSAGE: update from blog
